swagger: '2.0'
info:
  description: 'Projeto de encurtador de URL'
  version: '1.0.0'
  title: 'Encurtador de URL'
  contact:
    email: 'renan.admribeiro@mail.com'
host: 'localhost:8091'
basePath: '/api'
schemes:
  - 'http'
paths:
  /url/{hash}:
    get:
      summary: 'Redireciona para a url original'
      produces:
        - 'application/json'
      parameters:
        - in: path
          name: 'hash'
          description: 'Hash gerada da URL original'
          required: true
      responses:
        302:
          description: 'Redireciona para URL original'
        404:
          description: 'Hash não encontrada na base de dados'
        500:
          description: 'Erro inesperado'
    put:
      summary: 'Atualiza a url original'
      consumes:
        - 'application/json'
      produces:
        - 'application/json'
      parameters:
        - in: path
          name: 'hash'
          description: 'Hash gerada da URL original'
          required: true
        - in: body
          name: 'body'
          description: 'URL original atualizada'
          required: true
          schema:
            type: object
            properties:
              fullURL:
                type: string
                example: 'https://www.example.com'
      responses:
        200:
          description: 'URL original atualizada com sucesso'
          schema:
            type: object
            properties:
              fullURL:
                type: string
                example: 'https://www.example.com'
              shortURL:
                type: string
                example: 'localhost:8091/xm7f8'
        404:
          description: 'Hash não encontrada na base de dados'
        500:
          description: 'Erro inesperado'
    delete:
      summary: 'Deleta a url original'
      produces:
        - 'application/json'
      parameters:
        - in: path
          name: 'hash'
          description: 'Hash gerada da URL original'
          required: true
      responses:
        204:
          description: 'URL original deletada com sucesso'
        404:
          description: 'Hash não encontrada na base de dados'
        500:
          description: 'Erro inesperado'
  /url/generate:
    post:
      summary: 'Gera uma url curta com base na url original'
      consumes:
        - 'application/json'
      produces:
        - 'application/json'
      parameters:
        - in: body
          name: 'body'
          description: 'URL original para gerar a URL curta'
          required: true
          schema:
            type: object
            properties:
              fullURL:
                type: string
                example: 'https://www.example.com'
      responses:
        201:
          description: 'URL curta gerada com sucesso'
          schema:
            type: object
            properties:
              fullURL:
                type: string
                example: 'https://www.example.com'
              shortURL:
                type: string
                example: 'localhost:8091/xm7f8'
        409:
          description: 'URL curta já existe na base de dados'
        500:
          description: 'Erro inesperado'
externalDocs:
  description: 'My application'
  url: 'http://swagger.io'
