version: '2.4'
services:
  api:
    container_name: api
    build:
      context: .
      Dockerfile: Dockerfile
    ports:
      - "8091:8091"
    restart: always
    env_file: ./.env.local  
    tty: true
    stdin_open: true
    depends_on:
      - mongo
    networks:
      - host
        
  mongo:
    image: mongo
    restart: always
    container_name: mongo
    ports:
      - 27017:27017     
    networks:
      - host
networks: 
  host:
    driver: bridge 
    