name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:

  mongodbAndBack:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      
      - name: Run install
        run: |
          cd Back
          npm install
      
      - name: Run test
        run: |
          cd Back
          npm run test
             
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: encurtador-url-node
          IMAGE_TAG: ${{github.sha}}
        run: |
          cd Back
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      
  build-and-deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Frontend
        uses: actions/checkout@v2
        with:
          path: 'frontend'
          ref: main

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWD }}

      - name: Build and Push Frontend Image
        env:
          DOCKER_USERNAME: ${{ secrets.USER }}
          DOCKER_REPOSITORY: 'renanribeiro91/encurtador-url'
          DOCKER_TAG: 'latest'
        run: |
          cd frontend/front
          docker build -t $DOCKER_REPOSITORY:$DOCKER_TAG .
          docker push $DOCKER_REPOSITORY:$DOCKER_TAG
