name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:

  build-and-deploy-mongo-node:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      
      - name: Run install
        run: |
          cd Back
          npm install
      
      - name: Run test
        run: |
          cd Back
          npm run test
             
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: encurtador-url-node
          IMAGE_TAG: ${{github.sha}}
        run: |
          cd Back
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Deploy to Amazon ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          cluster: encurtador-url-Cluster
          service: encurtador-url-grupo
          image: $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          aws-region: sa-east-1

      
  build-and-deploy-frontend:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        cd front
        npm install

    - name: Build
      run: |
        cd front
        npm run build

    - name: Deploy to S3
      run: |
        cd front
        aws s3 sync build/ s3://${{ secrets.AWS_S3_BUCKET }} --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-east-1'
        SOURCE_DIR: 'build'     
